-- 2025-02-24 BugCourt Create Table sql V0.1 sleepyjelly  


MARIA_DB
2000
82%
Table: 8



CREATE TABLE bugcourt.TN_BBS
(
  BBS_SN       BIGINT         NOT NULL COMMENT 'board serial number(게시판 일련번호)',
  BBS_DVSN_CD  VARCHAR(30)   NULL     COMMENT 'board division code(게시판 구분 코드)',
  BBS_TITLE    VARCHAR(300)  NULL     COMMENT 'board ',
  BBS_TAG      VARCHAR(50)   NULL     COMMENT 'BBS TAG',
  BBS_CN       VARCHAR(4000) NOT NULL COMMENT 'BBS CONTEXT)',
  VIEWS        BIGINT         NULL     COMMENT 'VIEWS',
  RESPNS_SN    BIGINT         NOT NULL COMMENT 'USER RESPONSE SN (LIKE THUMBS UP)',
  DEL_YN       ENUM('Y', 'N') NULL     COMMENT 'Is Deleted (Y/N)',
  TEST_CASE_EX VARCHAR(2000) NULL     COMMENT 'example of test case',
  FILE_GRP_SN  BIGINT         NULL     COMMENT 'FILE_GROUP_SERIAL NUMBER (파일 그룹 일련번호)FILE_GROUP_SERIAL NUMBER (파일 그룹 일련번호)',
  FRST_REGR_ID VARCHAR(30)   NOT NULL COMMENT 'FIRST REGISTER ID',
  FRST_RER_DT  DATE           NOT NULL COMMENT 'FIRST REGISTED DATE',
  LAST_CHGR_ID VARCHAR(30)   NOT NULL COMMENT 'LAST CHANGER ID',
  LAST_CHG_DT  DATE           NOT NULL COMMENT 'LAST CHANGED DATE',
  PRIMARY KEY (BBS_SN)
) COMMENT 'BULLETIN BOARD SYSTEM  (BBS)(게시판)(揭示板) -> (bbs = board)  ';







CREATE TABLE bugcourt.TN_BBS_ANSWER 
(
  BBS_ANSWER_SN BIGINT        NOT NULL COMMENT 'board answer seriral number',
  BBS_SN        BIGINT        NOT NULL COMMENT 'board serial number(게시판 일련번호)',
  ANSWER_CNT    BIGINT        NULL     COMMENT 'submit a answer Count ',
  EXAMPLE_CODE  VARCHAR(4000) NULL     COMMENT 'Example Answer',
  DEL_YN        ENUM('Y', 'N')    NULL     COMMENT 'Is deleted Y / N (삭제 여부  Y,  N)',
  TEST_CASE     VARCHAR(4000) NOT NULL COMMENT 'test case',
  FILE_GRP_SN   BIGINT        NULL     COMMENT 'FILE_GROUP_SERIAL NUMBER (파일 그룹 일련번호)FILE_GROUP_SERIAL NUMBER (파일 그룹 일련번호)',
  FRST_REGR_ID  VARCHAR(30)   NOT NULL COMMENT 'FIRST REGISTER ID',
  FRST_RER_DT   DATE           NOT NULL COMMENT 'FIRST REGISTED DATE',
  LAST_CHGR_ID  VARCHAR(30)   NOT NULL COMMENT 'LAST CHANGER ID',
  LAST_CHG_DT   DATE           NOT NULL COMMENT 'LAST CHANGED DATE',
    PRIMARY KEY (BBS_ANSWER_SN)
) COMMENT 'Algorithm correct answer ';

CREATE TABLE bugcourt.TN_COMMENT
(
  COMMENT_SN     BIGINT        NOT NULL COMMENT 'Comment Serial Number (pk)',
  BBS_SN         BIGINT        NOT NULL COMMENT 'Board Serial Number ',
  COMMENT_CN     VARCHAR(4000) NOT NULL COMMENT 'comment cn',
  REF_COMMENT_SN BIGINT        NULL     COMMENT 'Reference Comment Sn',
  DEL_YN         ENUM('Y', 'N')    NULL     COMMENT 'is deleted y/n',
  FRST_REGR_ID   VARCHAR(30)   NOT NULL COMMENT 'FIRST REGISTER ID',
  FRST_RER_DT    DATE           NOT NULL COMMENT 'FIRST REGISTED DATE',
  LAST_CHGR_ID   VARCHAR(30)   NOT NULL COMMENT 'LAST CHANGER ID',
  LAST_CHG_DT    DATE           NOT NULL COMMENT 'LAST CHANGED DATE',
    PRIMARY KEY (COMMENT_SN)
);


CREATE TABLE bugcourt.TN_FILE
(
  FILE_GRP_SN   BIGINT        NOT NULL COMMENT 'PK(FILE_GRP_SN, FILE_SNO) , file serial number',
  FILE_SNO      INT   NOT NULL COMMENT 'file sequence number',
  LGC_FILE_NM   VARCHAR(100)  NULL     COMMENT 'logical file name',
  PHY_FILE_NM   VARCHAR(100)  NULL     COMMENT 'physical file name',
  FILE_SIZE     VARCHAR(4000) NULL     COMMENT 'file size',
  PHY_FILE_PATH VARCHAR(200)  NULL     COMMENT 'physical file path',
  FILE_STTS_CD  VARCHAR(20)   NULL     COMMENT 'file status code',
  FILE_DVSN_CD  VARCHAR(20)   NULL     COMMENT 'file division code',
  DEL_YN        ENUM('Y', 'N')    NULL     COMMENT 'is deleted y/n',
  FRST_REGR_ID  VARCHAR(30)   NOT NULL COMMENT 'FIRST REGISTER ID',
  FRST_RER_DT   DATE           NOT NULL COMMENT 'FIRST REGISTED DATE',
  LAST_CHGR_ID  VARCHAR(30)   NOT NULL COMMENT 'LAST CHANGER ID',
  LAST_CHG_DT   DATE           NOT NULL COMMENT 'LAST CHANGED DATE',
  UNIQUE KEY uniq_file_key (FILE_GRP_SN, FILE_SNO)
) COMMENT 'FILE ';



CREATE TABLE bugcourt.TN_FILE_GRP
(
  FILE_GRP_SN  BIGINT       NOT NULL COMMENT 'FILE_GROUP_SN',
  REF_TN_NM    VARCHAR(100) NOT NULL COMMENT 'REFERENCE TABLE NAME',
  DEL_YN       ENUM('Y', 'N')   NULL     COMMENT 'IS DELETED Y / N ',
  FRST_REGR_ID VARCHAR(30)  NOT NULL COMMENT 'FIRST REGISTER ID',
  FRST_RER_DT  DATE          NOT NULL COMMENT 'FIRST REGISTED DATE',
  LAST_CHGR_ID VARCHAR(30)  NOT NULL COMMENT 'LAST CHANGER ID',
  LAST_CHG_DT  DATE          NOT NULL COMMENT 'LAST CHANGED DATE',
  PRIMARY KEY (FILE_GRP_SN)
) COMMENT 'FILE GROUP';

CREATE TABLE bugcourt.TN_USER
(
  USER_ID          VARCHAR(30)   NOT NULL COMMENT 'ID',
  USER_PW          VARCHAR(200)  NOT NULL COMMENT 'Password ',
  USER_NM          VARCHAR(400)  NOT NULL COMMENT 'NAME',
  USER_DC          VARCHAR(4000) NULL     COMMENT 'DESCRIPTION	',
  USER_EMAIL       VARCHAR(200)  NOT NULL COMMENT 'Email',
  USER_PHONE       VARCHAR(20)   NULL     COMMENT 'Phone',
  USER_CMPNY       VARCHAR(100)  NULL     COMMENT 'COMPANY	',
  USER_GITHUB_LINK VARCHAR(100)  NULL     COMMENT 'USER_GITHUB_LINK',
  USER_PERMISSION  VARCHAR(100)  NOT NULL COMMENT 'USER_PERMISSION',
  USER_STATUS      VARCHAR(30)   NULL     COMMENT 'User Status',
  FILE_GRP_SN      BIGINT        NULL     COMMENT 'FILE_GROUP_ID',
  USER_2FACTOR_YN  ENUM('Y', 'N')    NULL     COMMENT 'is user using 2factor y/n',
  USER_2FACTOR_KEY VARCHAR(100)  NULL     COMMENT '2factor key',
  FRST_REGR_ID     VARCHAR(30)   NOT NULL COMMENT 'FIRST REGISTER ID',
  FRST_RER_DT      DATE           NOT NULL COMMENT 'FIRST REGISTED DATE',
  LAST_CHGR_ID     VARCHAR(30)   NOT NULL COMMENT 'LAST CHANGER ID',
  LAST_CHG_DT      DATE           NOT NULL COMMENT 'LAST CHANGED DATE',
  PRIMARY KEY (USER_ID)
) COMMENT 'USER';

CREATE TABLE bugcourt.TN_USER_ANSWER
(
  BBS_ANSWER_SN BIGINT NOT NULL COMMENT 'board answer seriral number',
  BBS_SN        BIGINT NOT NULL COMMENT 'board serial number(게시판 일련번호)',
  ANSWER_CN     VARCHAR(4000)        NULL     COMMENT 'answer cn ',
  IS_CORRECT     ENUM('Y', 'N')        NULL     COMMENT 'is correct y / n ',
  ERROR_LOG     VARCHAR(4000)        NULL     COMMENT 'error',
  LANG          VARCHAR(100)        NULL     COMMENT 'algorithm language',
  STTUS         VARCHAR(30)        NULL     COMMENT 'status of answer',
    PRIMARY KEY (BBS_ANSWER_SN)
) COMMENT 'submited answer from user';

CREATE TABLE bugcourt.TN_USER_RESPNS
(
  RESPNS_SN    BIGINT      NOT NULL COMMENT 'serial number',
  RESPNS_TYPE  ENUM('Y', 'N')  NOT NULL COMMENT 'Y - Thumbs up N - Thumbs down',
  REF_TN       VARCHAR(30) NULL     COMMENT 'TABLE NAME',
  REF_TN_SN    BIGINT      NULL     COMMENT 'Reference table serial number(pk)',
  USER_ID      VARCHAR(30) NULL     COMMENT 'userId',
  FRST_REGR_ID VARCHAR(30) NOT NULL COMMENT 'FIRST REGISTER ID',
  FRST_RER_DT  DATE         NOT NULL COMMENT 'FIRST REGISTED DATE',
  LAST_CHGR_ID VARCHAR(30) NOT NULL COMMENT 'LAST CHANGER ID',
  LAST_CHG_DT  DATE         NOT NULL COMMENT 'LAST CHANGED DATE',
  PRIMARY KEY (RESPNS_SN)
) COMMENT 'about user response';

